http:
  env: uat
  port: 8082
  prefix: auth-service
  timeout: 5000
  retryCount: 3
  retryDelay: 500

swagger:
  title: 管理后台
  version: 1.0
  prefix: api-docs
  description: 管理后台接口文档

DBConnections:
  - enable: true
    options:
      name: CORE_SERVICE_DB
      uri: ${CORE_SERVICE_DB}

cors:
  allowedHeaders:
    - X-timestamp
    - Access-Token
    - Accept
    - Content-Type
    - X-Sign
    - x-locale
    - Locale
  origin:
    - http://localhost:3001
  credentials: true
  optionsSuccessStatus: 204
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
