http:
  env: prod
  port: 8080
  prefix: api
  timeout: 5000
  retryCount: 3
  retryDelay: 500

documentService:
  baseURL: localehost:8082/api/document

swagger:
  title: 管理后台
  version: 1.0
  prefix: api-docs
  description: 管理后台接口文档

DBConnections:
  - enable: true
    options:
      name: CORE_SERVICE_DB
      uri: ${CORE_SERVICE_DB}

microServices:
  - name: core-service
    enable: true
    options:
      host: ${CORE_SERVICE_HOST}
      port: 8081

cors:
  allowedHeaders:
    - X-timestamp
    - Access-Token
    - Accept
    - Content-Type
    - X-Sign
    - x-locale
    - Locale
  origin:
    - https://pawhaven.work
  optionsSuccessStatus: 204
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS
    - HEAD
    - PATCH

limitation:
  ttl: 60
  limit: 1000

auth:
  secret: aoda+zyr
  ttl: 4h
  refreshSecret: '^zyr&aoda^'
  refreshTTL: 3d
  saltRounds: 10
  privateKey: ${AUTH_PRIVATEKEY}
  requestGap: 120
  enableSign: true
  rootUser: LOVE

health:
  ping:
